ESODBExportNPC = {}
ESODBExportNPC.List = {
	{
		DE = "schlammkrabbe",
		EN = "mudcrab",
		FR = "vasard",
		RU = "грязевой краб",
		Key = "MudCrabKills",
	},
	{
		DE = "schwärmende schlammkrabbe",
		EN = "swarming mudcrab",
		FR = "vasard en nuée",
		RU = "грязевой краб из стаи",
		Key = "MudCrabKills",
	},
	{
		DE = "prachtvolle schlammkrabbe",
		EN = "prodigious mudcrab",
		FR = "vasard prodigieux",
		RU = "чудовищный грязевой краб",
		Key = "MudCrabKills",
	},
	{
		DE = "kuh",
		EN = "cow",
		FR = "vache",
		RU = "корова",
		Key = "CowKills",
	},
	{
		DE = "ochse",
		EN = "ox",
		FR = "bœuf",
		RU = "вол",
		Key = "CowKills",
	},
	{
		DE = "bulle",
		EN = "bull",
		FR = "taureau",
		RU = "бык",
		Key = "CowKills",
	},
	{
		DE = "huhn",
		EN = "chicken",
		FR = "poulet",
		RU = "kурица",
		Key = "ChickenKills",
	},
	{
		DE = "reh",
		EN = "deer",
		FR = "biche",
		RU = "олень",
		Key = "DeerKills",
	},
	{
		DE = "ziege",
		EN = "goat",
		FR = "chèvre",
		RU = "коза",
		Key = "GoatKills",
	},
	{
		DE = "schafsbock",
		EN = "sheep",
		FR = "mouton",
		RU = "баран",
		Key = "SheepKills",
	},
	{
		DE = "schaf",
		EN = "sheep",
		FR = "brebis",
		RU = "овца",
		Key = "SheepKills",
	},
	{
		DE = "eidechse",
		EN = "lizard",
		FR = "lézard",
		RU = "ящерица",
		Key = "LizardKills",
	},
	{
		DE = "schwein",
		EN = "pig",
		FR = "cochon",
		RU = "свинья",
		Key = "PigKills",
	},
	{
		DE = "hase",
		EN = "rabbit",
		FR = "lapin",
		RU = "кролик",
		Key = "RabbitKills",
	},
	{
		DE = "ratte",
		EN = "rat",
		FR = "rat",
		RU = "крыс",
		Key = "RatKills",
	},
	{
		DE = "eichhörnchen",
		EN = "squirrel",
		FR = "écureuil",
		RU = "белка",
		Key = "SquirrelKills",
	},
	{
		DE = "spinne",
		EN = "spider",
		FR = "araignée",
		RU = "паук",
		Key = "SpiderKills",
	},
	{
		DE = "bantamguar",
		EN = "bantam guar",
		FR = "guar basset",
		RU = "бентамский гуар",
		Key = "BantamGuarKills",
	},
	{
		DE = "guar",
		EN = "guar",
		FR = "guar",
		RU = "гуар",
		Key = "GuarKills",
	},
	{
		DE = "bär",
		EN = "bear",
		FR = "ours",
		RU = "медведь",
		Key = "BearKills",
	},
	{
		DE = "zorntatzen-bär",
		EN = "rageclaw bear",
		FR = "ours ragegriffe",
		RU = "медведь клана яростного клыка",
		Key = "BearKills",
	},
	{
		DE = "tollwütiger bär",
		EN = "rabid bear",
		FR = "ours enragé",
		RU = "бешеный медведь",
		Key = "BearKills",
	},
	{
		DE = "skeever",
		EN = "skeever",
		FR = "skeever",
		RU = "skeever",
		Key = "SkeeverKills",
	},
	{
		DE = "kamel",
		EN = "camel",
		FR = "dromadaire",
		RU = "верблюд",
		Key = "CamelKills",
	},
	{
		DE = "affe",
		EN = "monkey",
		FR = "singe",
		RU = "обезьянка",
		Key = "MonkeyKills",
	},
	{
		DE = "fuchs",
		EN = "fox",
		FR = "renard",
		RU = "лиса",
		Key = "FoxKills",
	},
	{
		DE = "frosch",
		EN = "frog",
		FR = "grenouille",
		RU = "лягушка",
		Key = "FrogKills",
	},
	{
		DE = "skorpion",
		EN = "scorpion",
		FR = "scorpion",
		RU = "скорпион",
		Key = "ScorpionKills",
	},
	{
		DE = "skrib",
		EN = "scrib",
		FR = "scrib",
		RU = "скриб",
		Key = "ScribKills",
	},
	{
		DE = "käfer",
		EN = "beetle",
		FR = "scarabée",
		RU = "beetle",
		Key = "BeetleKills",
	},
	{
		DE = "aasfresser",
		EN = "skavenger",
		FR = "skraveine",
		RU = "падальщик",
		Key = "SkavengerKills",
	},
	{
		DE = "fennek",
		EN = "fennec fox",
		FR = "fennec",
		FRUR = "фенек",
		Key = "FennecFoxKills",
	},
	{
		DE = "sandschabe",
		EN = "sandroach",
		FR = "cafasable",
		RU = "песчаный таракан",
		Key = "SandroachKills",
	},
	{
		DE = "dornengecko",
		EN = "thorn gecko",
		FR = "gecko épineux",
		RU = "шипастый геккон",
		Key = "ThornGeckoKills",
	},
	{
		DE = "kahlläufer",
		EN = "fellrunner",
		FR = "coursimpie",
		RU = "быстроножка",
		Key = "FellrunnerKills",
	},
	{
		DE = "dolchrücken",
		EN = "daggerback",
		FR = "sanglineur",
		RU = "шипоспин",
		Key = "DaggerbackKills",
	},
	{
		DE = "wurmmaul",
		EN = "wormmouth",
		FR = "bouchever",
		RU = "черверот",
		Key = "WormmouthKills",
	},
	{
		DE = "daedratte",
		EN = "daedrat",
		FR = "daedrat",
		RU = "даэдрыса",
		Key = "DaedratKills",
	},
	{
		DE = "echalette",
		EN = "echalette",
		FR = "échalette",
		RU = "эшалет",
		Key = "EchaletteKills",
	},
	{
		DE = "döbeltaucher",
		EN = "chub loon",
		FR = "gros fou",
		RU = "пухлая гагара",
		Key = "ChubLoonKills",
	},
	{
		DE = "taschenmammut",
		EN = "pocket mammoth",
		FR = "mammouth de poche",
		RU = "карликовый мамонт",
		Key = "PocketMammothKills",
	},
	{
		DE = "horker",
		EN = "horker",
		FR = "horqueur",
		RU = "хоркер",
		Key = "HorkerKills",
	},
	{
		DE = "elch",
		EN = "elk",
		FR = "élan",
		RU = "олень",
		Key = "ElkKills",
	},
	{
		DE = "sepnatter",
		EN = "sep adder",
		FR = "aspic de sep",
		RU = "аспид сепа",
		Key = "SepAdderKills",
	},
	{
		DE = "drachenfrosch",
		EN = "dragon frog",
		FR = "grenouille dragon",
		RU = "лягушка-дракон",
		Key = "DragonFrogKills",
	},
	{
		DE = "reiher",
		EN = "heron",
		FR = "héron",
		RU = "цапля",
		Key = "HeronKills",
	},
	{
		DE = "gabelbock",
		EN = "antelope",
		FR = "antilope",
		RU = "антилопа",
		Key = "AntelopeKills",
	},
	{
		DE = "fiendroth",
		EN = "fiendroth",
		FR = "monstroth",
		RU = "финдрот",
		Key = "FiendrothKills",
	},
	{
		DE = "hundertfüßer",
		EN = "centipede",
		FR = "mille-pattes",
		RU = "сороконожка",
		Key = "CentipedeKills",
	},
	{
		DE = "drache",
		EN = "dragon",
		FR = "dragon",
		RU = "дракон",
		Key = "DragonKills",
	},
}


----
---  Functions
----
function ESODBExportNPC:GetSpecialNPCKey(targetName)

	local npcKey
	targetName = string.lower(zo_strformat("<<1>>", targetName))

	for _, npcInfo in pairs(ESODBExportNPC.List) do
		if(targetName == npcInfo.DE or targetName == npcInfo.EN or targetName == npcInfo.FR or targetName == npcInfo.RU) then
			npcKey = npcInfo.Key
		end
	end

	return npcKey
end